routes/web.php
    Route::resource('communication_template_type', 'CommunicationTemplateTypeController');
    
    //Get Communication Template Type status change
    Route::get('changeStatusCommunicationTemplateType', 'CommunicationTemplateTypeController@changeCommunicationTemplateTypeStatus');
    
    //Download Communication Template Type
    
    Route::get('communication_template_type/download-communication_template_type-excel', 'CommunicationTemplateTypeController@communication_template_typeDownload')->name('communication_template_type.download-communication_template_type-excel');
    
    // ---------------- Communication Template Type ---------------------------
    
    
    Route::get('area/download-area-excel', 'AreaController@allAreaDownload')->name('area.download-area-excel');
    
    
    //Get Product Resource
    Route::resource('products', 'ProductController');
    //Get Product dashboard
    Route::get('product/dashboard', 'ProductController@dashboard');
    //Get Product status change
    Route::get('changeStatusProduct', 'ProductController@changeProductStatus');
    //Download Category
    
    Route::get('product/download-product-excel', 'ProductController@productDownload')->name('product.download-product-excel');
    
    //Get User Resource
    Route::resource('users', 'User\UserController');
    Route::get('user/download-user-excel', 'User\UserController@userDownload')->name('user.download-user-excel');
    Route::resource('roles','User\RoleController');
    //Get User dashboard
    Route::get('user/dashboard', 'User\UserController@dashboard');
    //Get User status change
    Route::get('changeStatusUser', 'User\UserController@changeUserStatus');
    
    //Get State Resource
    Route::resource('states', 'StateController');
    //Get State dashboard
    Route::get('state/dashboard', 'StateController@dashboard');
    //Download State
    
    Route::get('state/download-state-excel', 'StateController@stateDownload')->name('state.download-state-excel');
    //Get City Resource
    Route::resource('cities', 'CityController');
    //Get City dashboard
    Route::get('city/dashboard', 'CityController@dashboard');
    //Upload City
    Route::post('city/upload-city-excel', 'CityController@uploadCity')->name('city.upload-city-excel');
    //Download city
    Route::get('city/download-city-excel', 'CityController@cityDownload')->name('city.download-city-excel');
    Route::get('city/download-allcity-excel', 'CityController@allCityDownload')->name('allcity.download-allcity-excel');
    //Get Area Resource
    Route::resource('areas', 'AreaController');
    //Upload Area
    Route::post('area/upload-area-excel', 'AreaController@uploadArea')->name('area.upload-area-excel');
    //Get Area dashboard
    Route::get('area/dashboard', 'AreaController@dashboard');
    Route::get('get-city-list','AreaController@getCityList');
    Route::get('get-area-list','AreaController@getAreaList');
    
    //Get VoucherType Resource
    Route::resource('vouchertype', 'Campaign\VoucherTypeController');
    //Get VoucherType Dashboard
    Route::get('voucher-type/dashboard', 'Campaign\VoucherTypeController@dashboard');
    Route::get('voucher-type/download-voucher-type-excel', 'Campaign\VoucherTypeController@voucherTypeDownload')->name('voucher-type.download-voucher-type-excel');
    //Get VoucherType Resource
    Route::resource('voucherspecification', 'Campaign\VoucherSpecificationController');
    //Get VoucherType Dashboard
    Route::get('voucher-specification/dashboard', 'Campaign\VoucherSpecificationController@dashboard');
    Route::get('voucher-specification/download-voucher-specification-excel', 'Campaign\VoucherSpecificationController@voucherSpecificationDownload')->name('voucher-specification.download-voucher-specification-excel');
    //post ajax request for checking values exists or not
    Route::post('getVoucher_specification','Campaign\VoucherSpecificationController@getVoucher_specification');
    
    //Get Delivery Mechanic Type Resource
    Route::resource('deliverymechanictype','Campaign\DeliveryMechanicTypeController');
    //Get Delivery Mechanic Type Dashboard

    Route::get('deliverymechanic-type/dashboard', 'Campaign\DeliveryMechanicTypeController@dashboard');
    Route::get('deliverymechanic-type/download-deliverymechanic-type-excel', 'Campaign\DeliveryMechanicTypeController@deliveryMechanicTypeDownload')->name('deliverymechanic-type.download-deliverymechanic-type-excel');
    //Get Promo TypeResource
    Route::resource('promotype','Campaign\PromoTypeController');
    //Get Promo Type Dashboard
    Route::get('promo-type/dashboard', 'Campaign\PromoTypeController@dashboard');
    Route::get('promo-type/download-promo-type-excel', 'Campaign\PromoTypeController@promoTypeDownload')->name('promo-type.download-promo-type-excel');
    //Get Company Resource
    Route::resource('companies','Campaign\CompanyController');
    //Get Company Dashboard
    Route::get('company/dashboard', 'Campaign\CompanyController@dashboard');
    Route::get('company/download-company-excel', 'Campaign\CompanyController@companyDownload')->name('company.download-company-excel');
    //Get Campaign Type Resource
    Route::resource('campaigntype','Campaign\CampaignTypeController');
    //Get Campaign Type Dashboard
    Route::get('campaign-type/dashboard', 'Campaign\CampaignTypeController@dashboard');
    
    //Get Venue  Resource
    Route::resource('venues','Pd\VenueController');
    //Get Venue  Resource
    Route::resource('venue-qc','Pd\VenueQcController');
    Route::resource('qc-rejected-venue','Pd\QCRejectedVenueController');
    //Get Venue  Resource
    Route::resource('target-assign','Pd\TargetAssignController');
    //Get Venue  Dashboard
    Route::get('venue/dashboard', 'Pd\VenueController@dashboard');
    //Get Product List On Venue Module
    Route::get('get-product-list','Pd\VenueController@getProductList');
    //Upload Venue Location On Venue Module
    Route::post('venue/upload-venue-location-excel', 'Pd\VenueController@uploadVenueLocation')->name('venue.upload-venue-location-excel');
    
    //Get Campaign  Resource
    Route::resource('campaigns','Campaign\CampaignController');
    //Get Campaign Dashboard
    Route::get('campaign/dashboard','Campaign\CampaignController@dashboard');
    //Get Category Export Excel
    Route::get('export_category/excel', 'CategoryController@categoryExportExcel')->name('export_category.excel');
    //Get Product Rule  Resource
    Route::resource('productrules','ProductRuleController');
    Route::get('changingProduct', 'ProductRuleController@changingProduct');
    //Get Generate Code  Resource
    Route::resource('generate_codes','Campaign\GenerateCodesController');
    
    Route::get('cronjob','CronJobController@store');
    
    Route::get('generate_code/csv-download/{id}','Campaign\GenerateCodesController@csvDownload');
    
    Route::resource('mobile-usage-rules','Campaign\MobileUsageRuleController');
    //Get Code  Resource
    Route::get('generate_code/voucher_code/{id}','Campaign\GenerateCodesController@allVoucherCode')->name('generate_code.voucher_code');
    Route::get('generate_code/download-voucher-excel/{id}', 'Campaign\GenerateCodesController@voucherCodeDownload')->name('voucher.download-voucher-excel');
    // Get ProductList Dropdown on behalf of campaign ID
    Route::get('get_genproductList','Campaign\GenerateCodesController@get_genProductList');

    // Get Product NameList Dropdown on behalf of campaign ID
    Route::get('get_genproductName','Campaign\GenerateCodesController@get_genProductName');
    //Campaign Details Resource
    Route::resource('campaign_details','Campaign\CampaignDetailsController');
    // Get ProductRuleList for Campaign Detail Page Dropdown on behalf of product ID
    Route::get('get_ProductRuleList','Campaign\CampaignDetailsController@get_ProductRuleList');
    //Tag Campaign Venue Resource
    Route::resource('tag_campaign_venues','Campaign\TagCampaignVenueController');    
    Route::get('tag_campaign_venues/{campaign_id}/{product_id}','Campaign\TagCampaignVenueController@show')->name('tag_campaign_venues.show');
    Route::get('tag_campaign_venues/{campaign_id}/{product_id}/edit','Campaign\TagCampaignVenueController@edit')->name('tag_campaign_venues.edit');
    Route::PATCH('tag_campaign_venues/{campaign_id}/{product_id}','Campaign\TagCampaignVenueController@update')->name('tag_campaign_venues.update');
    
    // Get ProductList Dropdown on behalf of campaign ID
    Route::get('get_productList','Campaign\TagCampaignVenueController@get_productList');

    // Get Product NameList Dropdown on behalf of campaign ID
    Route::get('get_productName','Campaign\TagCampaignVenueController@get_productName');

    // Get Venue list on behalf of City ID
    Route::get('cityTag_venueList','Campaign\TagCampaignVenueController@get_venueList');
    
    
    //------------Language ------------------------------------------//

    //Get Language dashboard
    Route::get('language/dashboard', function () {
    return view('admin.primary_language.dashboard');
    });

    // Get primary language
    Route::resource('primary_language','PrimaryLanguageController');

    //Get Category status change
    Route::post('changeStatus_primaryLanguage', 'PrimaryLanguageController@change_PrimaryLanguage_Status');

    //Get primary language Export Excel
    Route::get('export_primarylanguage/excel', 'PrimaryLanguageController@primarylanguage_ExportExcel')->name('export_primarylanguage.excel');
    
    //Other Language Resource
    Route::resource('otherlanguage','OtherLanguageController');  
   
    Route::get('export_otherlanguage/excel', 'OtherLanguageController@otherLanguageDownload')->name('export_otherlanguage.excel');
    //------------Language ------------------------------------------//
    //Get Operation Inbound dashboard
    Route::get('operation-management/dashboard', 'BookingAssignController@dashboard');

app/Http/Controllers/communication_template/create.blade.php
@extends('common.default')
@section('title', 'Category Create')
@section('content')
<!-- Main Content -->
<div id="content">
   <div class="container-fluid" style="margin-top: 20px;">
         <div class="d-sm-flex align-items-center justify-content-between pb-4">
            <h1 class="h3 mb-0 text-gray-800 border-left-primary  h-100 px-1 text-capitalize">add Communication Template</h1>
             <a href="{{url('admin/communication-template')}}" class="d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> &nbsp; Back</a>
        </div>
   <div class="container">
      <!-- Outer Row -->
      <div class="row justify-content-center">
         <div class="card login-card" style="width: 100%;">
            <div class="card-body p-0">
               <!-- Nested Row within Card Body -->
               <div class="row">
                  <div class="col-lg-12">
                     <div class="p-5">
                        @if ($errors->any())
                           <div class="alert alert-danger">
                             <ul>
                                 @foreach ($errors->all() as $error)
                                   <li>{{ $error }}</li>
                                 @endforeach
                             </ul>
                           </div><br />
                        @endif
                        <form class="user" action="{{ route('communication-template.store') }}" method="POST">
                           @csrf

                           <div class="form-group">
                              <label for="name" class="mr-sm-2">Subject:</label>
                              <input type="text" class="form-control form-control-user"
                              id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Subject Name" name="subject" value="{{ old('subject') }}">
                           </div>
                           <div class="form-group">
                              <label for="name" class="mr-sm-2">Template Content:</label>
                              <textarea class="ckeditor form-control" name="template-content"></textarea>
                           </div>
                           <div class="form-group">
                              <label for="name" class="mr-sm-2">SMS:</label>
                              <textarea  class="form-control form-control-user"
                              id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter SMS" name="sms" value="{{ old('sms') }}"></textarea>
                           </div>
                           
                           <a href="#" class="">
                           <button type="submit" class="btn btn-primary mt-4">Submit</button>
                           </a>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      
   </div>
</div>
</div>
<script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.ckeditor').ckeditor();
    });
</script>
<!-- End of Main Content -->
@stop

app/Http/Controllers/communication_template/dashboard.blade.php
@extends('common.default')
@section('content')
<!-- For demo purpose -->
    <div class="container">
         <div class="d-sm-flex align-items-center justify-content-between pt-5">
            <h1 class="h3 mb-0 text-gray-800 border-left-primary  h-100 px-1 text-capitalize">Category</h1>
             <a href="{{url('admin/dashboard')}}" class="d-none d-sm-inline-block btn btn-md btn-primary shadow-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> &nbsp;Back</a>
          </div>
          
               <div class="row" pb-4>
                  <div class="col-lg-12 mb-5 mt-5">
                     <div class="row">
                        
                        <div class="col-6 col-sm-6 col-md-2">
                           <div class="image-flip" ontouchstart="this.classList.toggle('hover');">
                              <div class="mainflip">
                                 <div class="frontside">
                                    <div class="card  shadow pb-0">
                                       <div class="card-body text-center">
                                          <a href="{{url('admin/categories')}}">
                                             <p class="icon" > <i class="fas fa-chart-line"></i></p>
                                          </a>
                                          <h3 class="h6 mb-0 text-uppercase  text-gray-800">
                                          Add Category</h4>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                        
                     </div>
                  </div>
               </div>
               
               
       
          
          
          
               
              
              <br><br>
               
               
               
            </div>
@stop

app/Http/Controllers/communication_template/edit.blade.php
@extends('common.default')
@section('title', 'Edit Category')
@section('content')
<!-- Main Content -->
<div id="content">
   <div class="container-fluid" style="margin-top: 20px;">
         <div class="d-sm-flex align-items-center justify-content-between pb-4">
            <h1 class="h3 mb-0 text-gray-800 border-left-primary  h-100 px-1 text-capitalize">Category</h1>
             <a href="{{url('admin/categories')}}" class="d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> &nbsp; Back</a>
        </div>
   <div class="container">
      <!-- Outer Row -->
      <div class="row justify-content-center"style="margin-top: 120px;">
         <div class="card login-card" style="width: 500px;">
            <div class="card-body p-0">
               <!-- Nested Row within Card Body -->
               <div class="row">
                  <div class="col-lg-12">
                     <div class="p-5">
                        @if ($errors->any())
                        <div class="alert alert-danger">
                           <ul>
                               @foreach ($errors->all() as $error)
                               <li>{{ $error }}</li>
                               @endforeach
                           </ul>
                        </div>
                        <br /> 
                        @endif
                        <form method="post" action="{{ route('categories.update', $categories->id) }}">
                           @method('PATCH') 
                           @csrf
                        
                           
                           <div class="form-group">
                              <input type="text" class="form-control form-control-user" id="exampleInputEmail" maxlength="20" aria-describedby="emailHelp" placeholder="Enter Category Name" name="name" value="{{$categories->name}}">
                           </div>
                           
                           <a href="#" class="">
                           <button type="submit" class="btn btn-primary btn-user btn-block mt-4">Update</button>
                           </a>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      
   </div>
</div>
</div>
<!-- End of Main Content -->
@stop
 

resources/views/admin/voucherspecification/create.blade.php
@extends('common.default')
@section('title', 'Voucher Specification Create')

@section('content')
<meta name="csrf-token" content="{!! csrf_token() !!}">
<!-- Main Content -->
<div id="content">
   <div class="container-fluid" style="margin-top:15px;">
     
      
            <div class="sub-headeing">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center   text-center text-sm-left" style="padding: 0px 20px;">
            <h3 class="font-w600   js-appear-enabled animated fadeIn" data-toggle="appear" style="color:#575757;font-weight: 600!important;font-size:20px">Voucher Specification</h3>
            <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
            <span class="d-inline-block js-appear-enabled animated fadeIn" data-toggle="appear" data-timeout="350">
            <a  href="{{url('admin/voucherspecification')}}" class="btn btn-primary btn-sm js-click-ripple-enabled" data-toggle="click-ripple" >
            <i class="fas fa-chevron-left mr-1"></i> Back
            </a>
            </span>
            </div>
            </div>
            </div>
        
   <div class="container">
      <!-- Outer Row -->
      <div class="row justify-content-center mt-5">
         <div class="card login-card" style="width: 500px;">
            <div class="card-body p-0">
               <!-- Nested Row within Card Body -->
               <div class="row">
                  <div class="col-lg-12">
                     <div class="p-5">
                        @if ($errors->any())
                           <div class="alert alert-danger">
                             <ul>
                                 @foreach ($errors->all() as $error)
                                   <li>{{ $error }}</li>
                                 @endforeach
                             </ul>
                           </div><br />
                        @endif
                        <div id="error_msg"></div>
                        <form id="frmvoucher_spec" class="user" action="{{ route('voucherspecification.store') }}" method="POST">
                           @csrf
                           <div class="form-group">
                                <label for="name" class="mr-sm-2">Voucher Type</label>
                              <select class="form-control" name="voucher_type_id" style="height: 45px;" onchange="voucher_type(this.value)">
                                 <option value="0">Select Voucher Type</option>
                                 @forelse($voucher_type as $voucher)
                                  <option value="{{$voucher->id}}" {{old('voucher_type_id') == $voucher->id ? 'Selected' : ''}}>{{$voucher->name}}</option>
                                 @empty
                                  <p>No Voucher Type List</p>
                                 @endforelse
                              </select>
                           </div>
                           <div id="physical"></div>
                           <div id="E_voucher"></div>      
                           <a href="#" class="">
                           <button type="button" class="btn btn-primary btn-user btn-block mt-4" onclick="submit_voucher()">Submit</button>
                           </a>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<!-- End of Main Content -->
@stop

resources/views/admin/voucherspecification/dashboard.blade.php
@extends('common.default')
@section('content')
<!-- For demo purpose -->
    <div class="container">
        <div class="d-sm-flex align-items-center justify-content-between pt-4">
                  <h1 class="h3 mb-0 text-gray-800 border-left-primary  h-100 px-1 text-capitalize">Voucher Specification</h1>
                  <a href="{{url('admin/dashboard')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> &nbsp; Back </a>
               </div>
               <div class="row" pb-4>
                  <div class="col-lg-12 mb-5 mt-5">
                      
                     <div class="row">
                        
                        
                        
                        <div class="col-6 col-sm-6 col-md-2">
                           <div class="image-flip" ontouchstart="this.classList.toggle('hover');">
                              <div class="mainflip">
                                 <div class="frontside">
                                    <div class="card  shadow pb-0">
                                       <div class="card-body text-center">
                                          <a href="{{url('admin/voucherspecification')}}">
                                             <p class="icon" > <i class="fas fa-ticket-alt"></i></p>
                                          </a>
                                          <h3 class="h6 mb-0 text-uppercase  text-gray-800">
                                          Add Voucher Specification</h4>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                        
                        
                     </div>
                  </div>
               </div>
               
               
               <div class="card shadow mb-4">
                  <div class="card-header py-3" style="background-color: #d33f3e;color: #FFF;">
                     <h6 class="m-0 font-weight-bold text-uppercase">Bar Chart</h6>
                  </div>
                  <div class="card-body">
                     <div class="chart-bar">
                        <canvas id="myBarChart"></canvas>
                     </div>
                  </div>
               </div>
            </div>
@stop

resources/views/admin/voucherspecification/index.blade.php
@extends('common.default')
@section('title', 'Voucher Specification List')
@section('content')
<!-- Main Content -->
<div id="content">
   <!-- Begin Page Content -->
   <div class="container-fluid" style="margin-top: 20px;">
      
      
    <div class="bg-primary-dark-op">
        <div class="content content-narrow content-full">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center   text-center text-sm-left" style="padding: 0px 20px;">
                <div class="flex-sm-fill">
                    <h3 class="font-w600   js-appear-enabled animated fadeIn" data-toggle="appear" style="color:#575757;font-weight: 600!important;font-size:20px">Voucher Specification</h3>
                    
                </div>
                <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
                    <span class="d-inline-block js-appear-enabled animated fadeIn" data-toggle="appear" data-timeout="350">
                        
                       
                            <a href="{{url('admin/voucherspecification/create')}}">  <button class="btn btn-danger btn-sm"    type="button" id="dropdownMenuButton">
                     <i class="fas fa-plus"></i> &nbsp; Add Voucher Specification
                     </button></a>
                              
                      <a href="{{route('voucher-specification.download-voucher-specification-excel')}}"><button class="btn btn-primary btn-sm" type="button" id="dropdownMenuButton">
                     <i class="fas fa-file-import"></i> &nbsp; Download Voucher Specification
                     </button></a>
                     
                     
                        <a  href="{{url('admin/voucher-type/dashboard')}}" class="btn btn-primary btn-sm    js-click-ripple-enabled" data-toggle="click-ripple" >
                            <i class="fas fa-chevron-left mr-1"></i> Back
                        </a>
                         
                    </span>
                </div>
            </div>
        </div>
    </div>
      
      <br>
      
      
      
      <div class="card">
        
      
         <div class="card-body" >
           @if(session()->get('success'))
          <div class="alert alert-success">
            {{ session()->get('success') }}  
          </div>
           @endif
            <div class="table-responsive">
               <table class="table  table-striped" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                     <tr style="text-transform: capitalize;color: #FFF;background-color: #d33f3e"  >
                        <th >SN</th>
                        <th>Voucher Specification ID</th>
                        <th>Voucher Specification Name</th>
                        <th>Voucher type Name</th>
                        
                        <th>Created By</th>
                        <th>Updated By</th>
                        <th>Created Date/Time</th>
                        <th>Updated Date/Time</th>
                        <th>Action</th>
                        <th>Status</th>
                        
                     </tr>
                  </thead>
                  <tbody>
                    <?php $i=1; ?>
                     @forelse($voucher_specification as $voucher)
                      
                    <tr>
                        <td>{{$i}}</td>
                        <td>{{$voucher->id}}</td>
                        <td>{{$voucher->size_name}}</td>
                        <td>{{$voucher->voucher_type['name']}}</td>
                        
                        <td>{{isset($voucher->created_user['name']) ? $voucher->created_user['name'] : 'NA'}}</td>
                        <td>{{isset($voucher->updated_user['name']) ? $voucher->updated_user['name'] : 'NA'}}</td>
                        <td>{{$voucher->created_at->format('d M Y')}}/{{$voucher->created_at->format('g:i A')}}</td>
                        <td>{{$voucher->updated_at->format('d M Y')}}/{{$voucher->updated_at->format('g:i A')}}</td>
                        <td>
                           <a href="{{ route('voucherspecification.show',$voucher->id) }}"><span style="color: blue;padding:5px;"><i class="fas fa-eye fa-primary fa-md"> </i></span></a>
                           
                           <a href="{{ route('voucherspecification.edit',$voucher->id)}}"><span style="color: black;padding:5px;"   ><i class="fas fa-edit fa-primary fa-md"></i></span></a>
                            
                        </td>
                        <td>
                            
                              <input data-id="{{$voucher->id}}" class="toggle-class categoryStatus" type="checkbox" 
                              data-onstyle="success" data-offstyle="danger" data-toggle="toggle" data-on="Active" 
                              data-off="InActive" {{ $voucher->status ==1 ? 'checked' : '' }}>  
                              <input type="hidden" name="mdoelName" id="mdoelName" value="VoucherSpecification">  
                        </td>
                    </tr>
                    <?php $i++; ?>
                    @empty
                    
                    @endforelse
                    
                  </tbody>
               </table>
            </div>
         </div>
      </div>
   </div>
   <!-- /.container-fluid -->
</div>
<!-- End of Main Content -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" ></script>
<script>
  $(function() {
    $('.toggle-class').change(function() {
        var status = $(this).prop('checked') == true ? '1' : '0'; 
        var category_id = $(this).data('id'); 
         
        $.ajax({
            type: "GET",
            dataType: "json",
            url: "{{url('/admin/changeStatusCategory')}}",
            data: {'status': status, 'category_id': category_id},
            success: function(data){
              console.log(data.success)
            }
        });
    })
  })
</script>
@stop