routes/web.php
    Route::post('venue/upload-venue-location-excel', 'Pd\VenueController@uploadVenueLocation')->name('venue.upload-venue-location-excel');
    
    //Get Campaign  Resource
    Route::resource('campaigns','Campaign\CampaignController');
    //Get Campaign Dashboard
    Route::get('campaign/dashboard','Campaign\CampaignController@dashboard');
    //Get Category Export Excel
    Route::get('export_category/excel', 'CategoryController@categoryExportExcel')->name('export_category.excel');
    //Get Product Rule  Resource
    Route::resource('productrules','ProductRuleController');
    Route::get('changingProduct', 'ProductRuleController@changingProduct');
    //Get Generate Code  Resource
    Route::resource('generate_codes','Campaign\GenerateCodesController');
    
    Route::get('cronjob','CronJobController@store');
    
    Route::get('generate_code/csv-download/{id}','Campaign\GenerateCodesController@csvDownload');
    
    Route::resource('mobile-usage-rules','Campaign\MobileUsageRuleController');
    //Get Code  Resource
    Route::get('generate_code/voucher_code/{id}','Campaign\GenerateCodesController@allVoucherCode')->name('generate_code.voucher_code');
    Route::get('generate_code/download-voucher-excel/{id}', 'Campaign\GenerateCodesController@voucherCodeDownload')->name('voucher.download-voucher-excel');
    // Get ProductList Dropdown on behalf of campaign ID
    Route::get('get_genproductList','Campaign\GenerateCodesController@get_genProductList');

    // Get Product NameList Dropdown on behalf of campaign ID
    Route::get('get_genproductName','Campaign\GenerateCodesController@get_genProductName');
    //Campaign Details Resource
    Route::resource('campaign_details','Campaign\CampaignDetailsController');
    // Get ProductRuleList for Campaign Detail Page Dropdown on behalf of product ID
    Route::get('get_ProductRuleList','Campaign\CampaignDetailsController@get_ProductRuleList');
    //Tag Campaign Venue Resource
    Route::resource('tag_campaign_venues','Campaign\TagCampaignVenueController');    
    Route::get('tag_campaign_venues/{campaign_id}/{product_id}','Campaign\TagCampaignVenueController@show')->name('tag_campaign_venues.show');
    Route::get('tag_campaign_venues/{campaign_id}/{product_id}/edit','Campaign\TagCampaignVenueController@edit')->name('tag_campaign_venues.edit');
    Route::PATCH('tag_campaign_venues/{campaign_id}/{product_id}','Campaign\TagCampaignVenueController@update')->name('tag_campaign_venues.update');
    
    // Get ProductList Dropdown on behalf of campaign ID
    Route::get('get_productList','Campaign\TagCampaignVenueController@get_productList');

    // Get Product NameList Dropdown on behalf of campaign ID
    Route::get('get_productName','Campaign\TagCampaignVenueController@get_productName');

    // Get Venue list on behalf of City ID
    Route::get('cityTag_venueList','Campaign\TagCampaignVenueController@get_venueList');
    
    
    //------------Language ------------------------------------------//

    //Get Language dashboard
    Route::get('language/dashboard', function () {
    return view('admin.primary_language.dashboard');
    });

    // Get primary language
    Route::resource('primary_language','PrimaryLanguageController');

    //Get Category status change
    Route::post('changeStatus_primaryLanguage', 'PrimaryLanguageController@change_PrimaryLanguage_Status');

    //Get primary language Export Excel
    Route::get('export_primarylanguage/excel', 'PrimaryLanguageController@primarylanguage_ExportExcel')->name('export_primarylanguage.excel');
    
    //Other Language Resource
    Route::resource('otherlanguage','OtherLanguageController');  
   
    Route::get('export_otherlanguage/excel', 'OtherLanguageController@otherLanguageDownload')->name('export_otherlanguage.excel');
    //------------Language ------------------------------------------//
    //Get Operation Inbound dashboard
    Route::get('operation-management/dashboard', 'BookingAssignController@dashboard');
    //Get customer Query status change
    Route::post('changeStatus_customerQuery', 'CustomerQueryController@changeCustomerQueryStatus');
    Route::resource('assign-type', 'AssignTypeController');
    Route::resource('booking-assign', 'BookingAssignController');
    Route::post('booking-assign/fetch_data', 'BookingAssignController@fetch_data')->name('booking-assign.fetch_data');
    // Get customer Query
    Route::resource('customerquery','CustomerQueryController');
    
    // Get customer Query
    Route::resource('operationinbound','OperationInboundController');
    
    //Get Customer Transaction History
    Route::get('customer-transaction-history','InboundModuleController@customerTransactionHistory');
    
    // ---------------- Operation Inbound Module starts here ------------------------------------//
    
        // Get Inbound Module form
        Route::get('inbound_module', function(){
            return view('admin.inbound_module.inbound_form');
        });

    Route::post('inbound_module/popup','InboundModuleController@popup');
    Route::get('inbound_module/booking_details','InboundModuleController@booking_details');
    Route::post('inbound_module/cancel_booking','InboundModuleController@cancel_booking');
    Route::get('inbound_module/check_request','InboundModuleController@check_request');
    Route::post('inbound_module/cannot_rescheduled','InboundModuleController@cannot_rescheduled');
    Route::post('inbound_module/can_rescheduled','InboundModuleController@can_rescheduled');
    Route::post('inbound_module/send_email_microsite_issue','InboundModuleController@send_email_microsite_issue');
    Route::post('inbound_module/send_email_venue_related_issue','InboundModuleController@send_email_venue_related_issue');
    Route::post('inbound_module/booking_confirmation','InboundModuleController@booking_confirmation');
    Route::post('inbound_module/unable_to_register','InboundModuleController@unable_to_register');
    Route::post('inbound_module/validity_related','InboundModuleController@validity_related');
    Route::post('inbound_module/contest_related','InboundModuleController@contest_related');
    Route::post('inbound_module/voucher_offer_code_related','InboundModuleController@voucher_offer_code_related');
    Route::post('inbound_module/reward_offer_code_resend','InboundModuleController@reward_offer_code_resend');
    Route::post('inbound_module/queryDetails','InboundModuleController@queryDetails');    
    Route::post('inbound_module/queryName','InboundModuleController@queryName');    
    
    // ---------------- Operation Inbound Module ends here -------------------------------------//
    
    //Get Operation Inbound dashboard
    Route::get('winner-campaign/dashboard', 'Winner\WinnerCampaignController@dashboard');

    // Winner Management
    Route::resource('winnercampaign','Winner\WinnerCampaignController');
    Route::resource('gifttype','Winner\GiftTypeController');
    Route::resource('setgiftallocation','Winner\SetGiftAllocationController');
    Route::resource('set-gift-attribute','Winner\GiftAttributeController');
    Route::resource('holiday-attribute','Winner\HolidayAttributeController');
    Route::resource('set-winner-frequency','Winner\SetWinnerFrequencyController');
    Route::resource('winner-data-upload','Winner\WinnerDataUploadController');
    Route::resource('winner-data-operation','Operation\WinnerDataOperationController');
    Route::resource('winner-agent','Winner\WinnerAgentController');
    
    
    
   // Route::get('target-assign','HomeController@targetAssign');
    Route::PATCH('venue-detail/{id}','Pd\VenueQcController@updateVenueDetail');
    Route::PATCH('rejected-venue-detail/{id}','Pd\QCRejectedVenueController@updateRejectedVenueDetail');
    Route::GET('voucher/generate-coupons','Campaign\GenerateCodesController@generateCoupons');
    
    Route::Post('generate_codes/store', function(){
        
        \Illuminate\Support\Facades\Artisan::call('queue:work');
        
    });
    Route::resource('communication-template','CommunicationTemplateController');
    
    Route::get('total-booking-report','Report\ReportController@totalBookingReport');
    Route::get('re-booking-report','Report\ReportController@reBookingReport');
    Route::get('cancel-booking-report','Report\ReportController@cancelBookingReport');
    Route::get('confirm-booking-report','Report\ReportController@confirmBookingReport');
    Route::get('venue-wise-booking-report','Report\ReportController@venueWiseBookingReport');
    
    Route::get('report/dashboard','Report\ReportController@dashboard');
    
    
     
});

//admin authenticate
Route::group(['middleware'=>['auth','QC'],'prefix'=> 'QC/',], function (){

    Route::get('dashboard','QC\HomeController@dashboard');
    Route::get('venue-list','QC\HomeController@getVenueList');
    Route::get('venue-detail/{id}','QC\HomeController@venueDetail');
    Route::PATCH('venue-detail/{id}','QC\HomeController@updateVenueDetail');
});
//Auth authenticate.
Auth::routes();
// Route::group(['middleware'=>['auth'],'prefix'=> '/',], function (){

//     // Get booking Agent dashboard
//     Route::get('booking-champion/dashboard','BookingChampionController@dashboard');
//     Route::resource('booking-champion/bookings','BookingChampionController');
//     Route::post('booking-champion/bookings/fetch_data', 'BookingChampionController@fetch_data')->name('bookings.fetch_data');
// });

Route::group(['middleware'=>['auth'],'prefix'=> '/',], function (){

// Get booking Agent dashboard
Route::get('booking-champion/dashboard','BookingChampionController@dashboard');
Route::resource('booking-champion/bookings','BookingChampionController');
Route::post('booking-champion/bookings/fetch_data', 'bookingchampioncontroller@fetch_data')->name('bookings.fetch_data');
route::post('booking-champion/bookings/popup','bookingchampioncontroller@popup')->name('bookings.popup');

app/CustomerQuery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CustomerQuery extends Model
{
    protected $table = 'tbl_customer_query';
    protected $fillable = ['name'];


   
}

app/Http/Controllers/CustomerQueryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\CustomerQuery;

class CustomerQueryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $customer_query = CustomerQuery::get();

        return view('admin.customer_query.index')->with([
        'customer_query'  => $customer_query
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.customer_query.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $this->validate($request, [
            'name'      => 'required|min:3|regex:/^[a-zA-Z\s]*$/',
            
      ]);

      CustomerQuery::create($validatedData);

      return redirect('admin/customerquery')->withSuccess('Customer Query has been created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $customer_query = CustomerQuery::find($id);
        return view('admin.customer_query.show',compact('customer_query'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customer_query = CustomerQuery::find($id);
        return view('admin.customer_query.edit', compact('customer_query'));       
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required|regex:/^[a-zA-Z\s]*$/',
            
        ]);        
        $customer_query = CustomerQuery::find($id);
        $customer_query->name =  $request->get('name');
        $customer_query->save();        
        return redirect('/admin/customerquery')->with('success', 'Customer query updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
    }

    public function changeCustomerQueryStatus(Request $request)
    {
        $customer_query = CustomerQuery::find($request->id);
        $customer_query->status = $request->status;
        $customer_query->save();
  
        return response()->json(['success'=>'Customer Query status change successfully.']);
    }
    
    
    
    
}

app/Http/Controllers/communication_template/create.blade.php
@extends('common.default')
@section('title', 'Category Create')
@section('content')
<!-- Main Content -->
<div id="content">
   <div class="container-fluid" style="margin-top: 20px;">
         <div class="d-sm-flex align-items-center justify-content-between pb-4">
            <h1 class="h3 mb-0 text-gray-800 border-left-primary  h-100 px-1 text-capitalize">add Communication Template</h1>
             <a href="{{url('admin/communication-template')}}" class="d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> &nbsp; Back</a>
        </div>
   <div class="container">
      <!-- Outer Row -->
      <div class="row justify-content-center">
         <div class="card login-card" style="width: 100%;">
            <div class="card-body p-0">
               <!-- Nested Row within Card Body -->
               <div class="row">
                  <div class="col-lg-12">
                     <div class="p-5">
                        @if ($errors->any())
                           <div class="alert alert-danger">
                             <ul>
                                 @foreach ($errors->all() as $error)
                                   <li>{{ $error }}</li>
                                 @endforeach
                             </ul>
                           </div><br />
                        @endif
                        <form class="user" action="{{ route('communication-template.store') }}" method="POST">
                           @csrf

                           <div class="form-group">
                              <label for="name" class="mr-sm-2">Subject:</label>
                              <input type="text" class="form-control form-control-user"
                              id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Subject Name" name="subject" value="{{ old('subject') }}">
                           </div>
                           <div class="form-group">
                              <label for="name" class="mr-sm-2">Template Content:</label>
                              <textarea class="ckeditor form-control" name="template-content"></textarea>
                           </div>
                           <div class="form-group">
                              <label for="name" class="mr-sm-2">SMS:</label>
                              <textarea  class="form-control form-control-user"
                              id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter SMS" name="sms" value="{{ old('sms') }}"></textarea>
                           </div>
                           
                           <a href="#" class="">
                           <button type="submit" class="btn btn-primary mt-4">Submit</button>
                           </a>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      
   </div>
</div>
</div>
<script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.ckeditor').ckeditor();
    });
</script>
<!-- End of Main Content -->
@stop

resources/views/admin/customer_query/create.blade.php
@extends('common.default')
@section('title', 'Customer Query Create')
@section('content')
<!-- Main Content -->
<div id="content">
   <div class="container-fluid" style="margin-top:15px;">
 
                  
        <div class="sub-headeing">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center   text-center text-sm-left" style="padding: 0px 20px;">
        <h3 class="module-title">Add Customer Query</h3>
        <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
        <span class="d-inline-block js-appear-enabled animated fadeIn" data-toggle="appear" data-timeout="350">
        <a  href="{{url('admin/customerquery')}}" class="btn btn-primary btn-sm    js-click-ripple-enabled" data-toggle="click-ripple" >
        <i class="fas fa-chevron-left mr-1"></i> Back
        </a>
        </span>
        </div>
        </div>
        </div>
        
    
   <div class="container">
      <!-- Outer Row -->
      <div class="row justify-content-center" style="margin-top:70px;">
         <div class="card login-card" style="width: 500px;">
            <div class="card-body p-0">
               <!-- Nested Row within Card Body -->
               <div class="row">
                  <div class="col-lg-12">
                     <div class="p-5">
                        @if ($errors->any())
                           <div class="alert alert-danger">
                             <ul>
                                 @foreach ($errors->all() as $error)
                                   <li>{{ $error }}</li>
                                 @endforeach
                             </ul>
                           </div><br />
                        @endif
                        <form class="user" action="{{ route('customerquery.store') }}" method="POST">
                           @csrf
                           <div class="form-group">
                               <label for="name" class="mr-sm-2">Enter Customer Query</label>
                              <input type="text" class="form-control" placeholder="Enter Customer Query" name="name" value="{{ old('name') }}" autocomplete="off">
                           </div>
                           
                           <a href="#" class="">
                           <button type="submit" class="btn btn-primary  btn-block mt-4">Submit</button>
                           </a>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      
   </div>
</div>
</div>
<!-- End of Main Content -->
@stop

resources/views/admin/customer_query/edit.blade.php
@extends('common.default')
@section('title', 'Edit Primary Language')
@section('content')
<!-- Main Content -->
<div id="content">
   <div class="container-fluid" style="margin-top:15px;">
        
        
        <div class="sub-headeing">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center   text-center text-sm-left" style="padding: 0px 20px;">
        <h3 class="module-title">Customer Query</h3>
        <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
        <span class="d-inline-block js-appear-enabled animated fadeIn" data-toggle="appear" data-timeout="350">
        <a  href="{{url('admin/customerquery')}}" class="btn btn-primary btn-sm    js-click-ripple-enabled" data-toggle="click-ripple" >
        <i class="fas fa-chevron-left mr-1"></i> Back
        </a>
        </span>
        </div>
        </div>
        </div>
        
        
   <div class="container">
      <!-- Outer Row -->
      <div class="row justify-content-center"style="margin-top:70px;">
         <div class="card login-card" style="width: 500px;">
            <div class="card-body p-0">
               <!-- Nested Row within Card Body -->
               <div class="row">
                  <div class="col-lg-12">
                     <div class="p-5">
                        @if ($errors->any())
                        <div class="alert alert-danger">
                           <ul>
                               @foreach ($errors->all() as $error)
                               <li>{{ $error }}</li>
                               @endforeach
                           </ul>
                        </div>
                        <br /> 
                        @endif
                        <form method="post" action="{{ route('customerquery.update', $customer_query->id) }}">
                           @method('PATCH') 
                           @csrf
                        
                           
                           <div class="form-group">
                                 <label for="name" class="mr-sm-2">Edit Customer Query</label>
                              <input type="text" class="form-control" placeholder="Enter Customer Query" name="name" value="{{$customer_query->name}}" autocomplete="off">
                           </div>
                           
                           <a href="#" class="">
                           <button type="submit" class="btn btn-primary btn-user btn-block mt-4">Update</button>
                           </a>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      
   </div>
</div>
</div>
<!-- End of Main Content -->
@stop
 

resources/views/admin/customer_query/index.blade.php
@extends('common.default')
@section('title', 'Primary Language')
@section('content')

<meta name="csrf-token" content="{!! csrf_token() !!}">
<!-- Main Content -->
<div id="content">
   <!-- Begin Page Content -->
   <div class="container-fluid" style="margin-top:15px;">

    <div class="bg-image overflow-hidden" style="background-color: #f5f5f5;margin-bottom:15px">
    <div class="bg-primary-dark-op">
        <div class="content content-narrow content-full">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center   text-center text-sm-left" style="padding: 0px 20px;">
                <div class="flex-sm-fill">
                    <h3 class="module-title">Customer  Query</h3>
                    
                </div>
                <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
                    <span class="d-inline-block js-appear-enabled animated fadeIn" data-toggle="appear" data-timeout="350">
                        
                        <a href="{{route('customerquery.create')}}">  <button class="btn btn-danger btn-sm"    type="button" id="dropdownMenuButton">
                     <i class="fas fa-plus"></i> &nbsp; Add Customer  Query
                     </button></a>
                     
                     
                        
                        <a href="{{url('admin/operation-management/dashboard')}}" class="btn btn-primary btn-sm  js-click-ripple-enabled" data-toggle="click-ripple">
                            <i class="fas fa-chevron-left mr-1"></i> Back
                        </a>
                         
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>



      <div class="card">
         
        
         <div class="card-body" >
                
               @if(session()->get('success'))
                <div class="alert alert-success" id="customerStatusMsg">
                  {{ session()->get('success') }}  
                </div>
               @endif
            <div class="table-responsive">
               <table class="table  table-striped" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                     <tr style="text-transform: capitalize;color: #FFF;background-color: #d33f3e"  >
                        <th >S.No</th>
                        <th >ID</th>
                        <th>Customer Query</th>
                        <th >Created By</th>
                        <th>Created Date/Time</th>
                        <th>Action</th>
                        <th>Status</th>
                     </tr>
                  </thead>
                  <tbody>
                     <?php $i = 1;?>
                     @forelse($customer_query as $pl)
                      <tr>
                          <td>{{$i}}</td>
                          <td>{{$pl->id}}</td>
                          <td>{{$pl->name}}</td>
                          <td>{{Auth::user()->name}}</td>
                          <td>{{$pl->created_at->format('d M Y')}}/{{$pl->created_at->format('g:i A')}}</td>
                          <td>
                             <a href="{{ route('customerquery.show',$pl->id) }}"><span style="color: blue;padding:5px;"><i class="fas fa-eye fa-primary fa-md"> </i></span></a>
                             
                             <a href="{{ route('customerquery.edit',$pl->id)}}"><span style="color: black;padding:5px;"   ><i class="fas fa-edit fa-primary fa-md"></i></span></a>
                             <!--  <form action="{{ route('primary_language.destroy', $pl->id) }}" method="POST" id="delete-form-{{ $pl->id }}" style="display: none;">
                                  {{csrf_field()}}
                                  {{ method_field('DELETE') }}
                                  <input type="hidden" value="{{ $pl->id }}" name="id">
                             </form>
                             
                             <a href="" onclick="if (!confirm('Are you sure you want to delete?')) return; 
                              event.preventDefault(); document.getElementById('delete-form-{{ $pl->id }}').submit();">
                              <span style="color: red;padding:5px;"  ><i class="fas fa-trash fa-primary fa-md"></i></span></a>
                             <span style="color: green;padding:5px;" ><i class="fas fa-comments fa-primary fa-md"></i></span>
                             <span style="color: grey;"><i class="fas fa-search fa-primary fa-md"></i></span> -->
                             <td>
                                <input data-id="{{$pl->id}}" class="toggle-class customerQueryStatus" type="checkbox" data-onstyle="success" data-offstyle="danger" data-toggle="toggle" data-on="Active" data-off="InActive" {{ $pl->status ==1 ? 'checked' : '' }}>
                             </td> 
                          </td>
                      </tr>
                      <?php $i++; ?>
                    @empty
                      <p>No Customer Query</p>
                    @endforelse
                   </tbody>
               </table>
            </div>
         </div>
      </div>
   </div>
   <!-- /.container-fluid -->
</div>
<!-- End of Main Content -->

@stop

resources/views/admin/customer_query/show.blade.php
@extends('common.default')
@section('title', 'Show Primary Language')
@section('content')
<div id="content">
   <div class="container-fluid" style="margin-top:15px;">
    
        
        <div class="sub-headeing">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center   text-center text-sm-left" style="padding: 0px 20px;">
        <h3 class="module-title">Customer Query</h3>
        <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
        <span class="d-inline-block js-appear-enabled animated fadeIn" data-toggle="appear" data-timeout="350">
        <a  href="{{url('admin/customerquery')}}" class="btn btn-primary btn-sm    js-click-ripple-enabled" data-toggle="click-ripple" >
        <i class="fas fa-chevron-left mr-1"></i> Back
        </a>
        </span>
        </div>
        </div>
        </div>
        
        
  
           <div class="container" style="margin-top:50px;">
            <!-- Outer Row -->
            <div class="row justify-content-center">
            <div class="card" style="width: 70%;">
            <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
            <div class="col-lg-12">
            
            
            
            <div class="form-group">
                
            <div class="card-body col-md-12 col-lg-12">
            <p class="show-details">ID </p>
            {{ $customer_query->id }} 
            </div>
            
            <div class="card-body col-md-12 col-lg-12">
            <p class="show-details">Customer Query</p>
           {{$customer_query->name}}
            </div>
            
            
            <div class="card-body col-md-12 col-lg-12">
            <p class="show-details">Created By</p>
            {{Auth::user()->name}}
            </div>
            
            
            <div class="card-body col-md-12 col-lg-12">
            <p class="show-details">Created Date & Time</p>
                {{$customer_query->created_at->format('d M Y')}}/{{$customer_query->created_at->format('g:i A')}}
            </div>
            
            <div class="card-body col-md-12 col-lg-12">
            <p class="show-details">Status</p>
                 {{$customer_query->status == 1 ? 'Active':'Inactive'}}
            </div>
            
            
            
            </div>
            </div>
            </div>
            </div>
            </div>
            </div>
            </div>
  
 
    
   </div>
</div>
@stop