routes/web.php
    Route::get('voucher-specification/download-voucher-specification-excel', 'Campaign\VoucherSpecificationController@voucherSpecificationDownload')->name('voucher-specification.download-voucher-specification-excel');
    //post ajax request for checking values exists or not
    Route::post('getVoucher_specification','Campaign\VoucherSpecificationController@getVoucher_specification');
    
    //Get Delivery Mechanic Type Resource
    Route::resource('deliverymechanictype','Campaign\DeliveryMechanicTypeController');
    //Get Delivery Mechanic Type Dashboard

    Route::get('deliverymechanic-type/dashboard', 'Campaign\DeliveryMechanicTypeController@dashboard');
    Route::get('deliverymechanic-type/download-deliverymechanic-type-excel', 'Campaign\DeliveryMechanicTypeController@deliveryMechanicTypeDownload')->name('deliverymechanic-type.download-deliverymechanic-type-excel');
    //Get Promo TypeResource
    Route::resource('promotype','Campaign\PromoTypeController');
    //Get Promo Type Dashboard
    Route::get('promo-type/dashboard', 'Campaign\PromoTypeController@dashboard');
    Route::get('promo-type/download-promo-type-excel', 'Campaign\PromoTypeController@promoTypeDownload')->name('promo-type.download-promo-type-excel');
    //Get Company Resource
    Route::resource('companies','Campaign\CompanyController');
    //Get Company Dashboard
    Route::get('company/dashboard', 'Campaign\CompanyController@dashboard');
    Route::get('company/download-company-excel', 'Campaign\CompanyController@companyDownload')->name('company.download-company-excel');
    //Get Campaign Type Resource
    Route::resource('campaigntype','Campaign\CampaignTypeController');
    //Get Campaign Type Dashboard
    Route::get('campaign-type/dashboard', 'Campaign\CampaignTypeController@dashboard');
    
    //Get Venue  Resource
    Route::resource('venues','Pd\VenueController');
    //Get Venue  Resource
    Route::resource('venue-qc','Pd\VenueQcController');
    Route::resource('qc-rejected-venue','Pd\QCRejectedVenueController');
    //Get Venue  Resource
    Route::resource('target-assign','Pd\TargetAssignController');
    //Get Venue  Dashboard
    Route::get('venue/dashboard', 'Pd\VenueController@dashboard');
    //Get Product List On Venue Module
    Route::get('get-product-list','Pd\VenueController@getProductList');
    //Upload Venue Location On Venue Module
    Route::post('venue/upload-venue-location-excel', 'Pd\VenueController@uploadVenueLocation')->name('venue.upload-venue-location-excel');
    
    //Get Campaign  Resource
    Route::resource('campaigns','Campaign\CampaignController');
    //Get Campaign Dashboard
    Route::get('campaign/dashboard','Campaign\CampaignController@dashboard');
    //Get Category Export Excel
    Route::get('export_category/excel', 'CategoryController@categoryExportExcel')->name('export_category.excel');
    //Get Product Rule  Resource
    Route::resource('productrules','ProductRuleController');
    Route::get('changingProduct', 'ProductRuleController@changingProduct');
    //Get Generate Code  Resource
    Route::resource('generate_codes','Campaign\GenerateCodesController');
    
    Route::get('cronjob','CronJobController@store');
    
    Route::get('generate_code/csv-download/{id}','Campaign\GenerateCodesController@csvDownload');
    
    Route::resource('mobile-usage-rules','Campaign\MobileUsageRuleController');
    //Get Code  Resource
    Route::get('generate_code/voucher_code/{id}','Campaign\GenerateCodesController@allVoucherCode')->name('generate_code.voucher_code');
    Route::get('generate_code/download-voucher-excel/{id}', 'Campaign\GenerateCodesController@voucherCodeDownload')->name('voucher.download-voucher-excel');
    // Get ProductList Dropdown on behalf of campaign ID
    Route::get('get_genproductList','Campaign\GenerateCodesController@get_genProductList');

    // Get Product NameList Dropdown on behalf of campaign ID
    Route::get('get_genproductName','Campaign\GenerateCodesController@get_genProductName');
    //Campaign Details Resource
    Route::resource('campaign_details','Campaign\CampaignDetailsController');
    // Get ProductRuleList for Campaign Detail Page Dropdown on behalf of product ID
    Route::get('get_ProductRuleList','Campaign\CampaignDetailsController@get_ProductRuleList');
    //Tag Campaign Venue Resource
    Route::resource('tag_campaign_venues','Campaign\TagCampaignVenueController');    
    Route::get('tag_campaign_venues/{campaign_id}/{product_id}','Campaign\TagCampaignVenueController@show')->name('tag_campaign_venues.show');
    Route::get('tag_campaign_venues/{campaign_id}/{product_id}/edit','Campaign\TagCampaignVenueController@edit')->name('tag_campaign_venues.edit');
    Route::PATCH('tag_campaign_venues/{campaign_id}/{product_id}','Campaign\TagCampaignVenueController@update')->name('tag_campaign_venues.update');
    
    // Get ProductList Dropdown on behalf of campaign ID
    Route::get('get_productList','Campaign\TagCampaignVenueController@get_productList');

    // Get Product NameList Dropdown on behalf of campaign ID
    Route::get('get_productName','Campaign\TagCampaignVenueController@get_productName');

    // Get Venue list on behalf of City ID
    Route::get('cityTag_venueList','Campaign\TagCampaignVenueController@get_venueList');
    
    
    //------------Language ------------------------------------------//

    //Get Language dashboard
    Route::get('language/dashboard', function () {
    return view('admin.primary_language.dashboard');
    });

    // Get primary language
    Route::resource('primary_language','PrimaryLanguageController');

    //Get Category status change
    Route::post('changeStatus_primaryLanguage', 'PrimaryLanguageController@change_PrimaryLanguage_Status');

    //Get primary language Export Excel
    Route::get('export_primarylanguage/excel', 'PrimaryLanguageController@primarylanguage_ExportExcel')->name('export_primarylanguage.excel');
    
    //Other Language Resource
    Route::resource('otherlanguage','OtherLanguageController');  
   
    Route::get('export_otherlanguage/excel', 'OtherLanguageController@otherLanguageDownload')->name('export_otherlanguage.excel');
    //------------Language ------------------------------------------//
    //Get Operation Inbound dashboard
    Route::get('operation-management/dashboard', 'BookingAssignController@dashboard');
    //Get customer Query status change
    Route::post('changeStatus_customerQuery', 'CustomerQueryController@changeCustomerQueryStatus');
    Route::resource('assign-type', 'AssignTypeController');
    Route::resource('booking-assign', 'BookingAssignController');
    Route::post('booking-assign/fetch_data', 'BookingAssignController@fetch_data')->name('booking-assign.fetch_data');
    // Get customer Query
    Route::resource('customerquery','CustomerQueryController');
    
    // Get customer Query
    Route::resource('operationinbound','OperationInboundController');
    
    //Get Customer Transaction History
    Route::get('customer-transaction-history','InboundModuleController@customerTransactionHistory');
    
    // ---------------- Operation Inbound Module starts here ------------------------------------//
    
        // Get Inbound Module form
        Route::get('inbound_module', function(){
            return view('admin.inbound_module.inbound_form');
        });

    Route::post('inbound_module/popup','InboundModuleController@popup');
    Route::get('inbound_module/booking_details','InboundModuleController@booking_details');
    Route::post('inbound_module/cancel_booking','InboundModuleController@cancel_booking');
    Route::get('inbound_module/check_request','InboundModuleController@check_request');
    Route::post('inbound_module/cannot_rescheduled','InboundModuleController@cannot_rescheduled');
    Route::post('inbound_module/can_rescheduled','InboundModuleController@can_rescheduled');
    Route::post('inbound_module/send_email_microsite_issue','InboundModuleController@send_email_microsite_issue');
    Route::post('inbound_module/send_email_venue_related_issue','InboundModuleController@send_email_venue_related_issue');
    Route::post('inbound_module/booking_confirmation','InboundModuleController@booking_confirmation');
    Route::post('inbound_module/unable_to_register','InboundModuleController@unable_to_register');
    Route::post('inbound_module/validity_related','InboundModuleController@validity_related');
    Route::post('inbound_module/contest_related','InboundModuleController@contest_related');
    Route::post('inbound_module/voucher_offer_code_related','InboundModuleController@voucher_offer_code_related');
    Route::post('inbound_module/reward_offer_code_resend','InboundModuleController@reward_offer_code_resend');
    Route::post('inbound_module/queryDetails','InboundModuleController@queryDetails');    
    Route::post('inbound_module/queryName','InboundModuleController@queryName');    
    
    // ---------------- Operation Inbound Module ends here -------------------------------------//
    
    //Get Operation Inbound dashboard
    Route::get('winner-campaign/dashboard', 'Winner\WinnerCampaignController@dashboard');

    // Winner Management
    Route::resource('winnercampaign','Winner\WinnerCampaignController');
    Route::resource('gifttype','Winner\GiftTypeController');
    Route::resource('setgiftallocation','Winner\SetGiftAllocationController');
    Route::resource('set-gift-attribute','Winner\GiftAttributeController');
    Route::resource('holiday-attribute','Winner\HolidayAttributeController');
    Route::resource('set-winner-frequency','Winner\SetWinnerFrequencyController');
    Route::resource('winner-data-upload','Winner\WinnerDataUploadController');
    Route::resource('winner-data-operation','Operation\WinnerDataOperationController');
    Route::resource('winner-agent','Winner\WinnerAgentController');
    
    
    
   // Route::get('target-assign','HomeController@targetAssign');

app/MobileUsageRule.php
<?php

namespace App;
use App\UserStampsTrait;
use Illuminate\Database\Eloquent\Model;

class MobileUsageRule extends Model
{
    use UserStampsTrait;
    protected $table = 'tbl_mobile_usage_rules';
    protected $fillable = ['name'];

    //User  function
    public function created_user()
    {
    	return $this->belongsTo('App\User','created_by','id');
    }
    
    //User  function
    public function updated_user()
    {
    	return $this->belongsTo('App\User','updated_by','id');
    }
}

app/Http/Controllers/Campaign/MobileUsageRuleController.php
<?php

namespace App\Http\Controllers\Campaign;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\MobileUsageRule;

class MobileUsageRuleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $mobile_usage_rules = MobileUsageRule::get();

        return view('admin.mobileusagerule.index')->with([
        'mobile_usage_rules'  => $mobile_usage_rules
        
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.mobileusagerule.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $this->validate($request, [
            'name'      => 'required|min:3|max:255|string',
            
      ]);

      MobileUsageRule::create($validatedData);

      return redirect('admin/mobile-usage-rules')->withSuccess('You have successfully created a Mobile Usage Rule!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $mobile_usage_rules = MobileUsageRule::find($id);
        return view('admin.mobileusagerule.show',compact('mobile_usage_rules'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $mobile_usage_rules = MobileUsageRule::find($id);
        return view('admin.mobileusagerule.edit', compact('mobile_usage_rules'));       
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            
        ]);        
        $mobile_usage_rules = MobileUsageRule::find($id);
        $mobile_usage_rules->name =  $request->get('name');
        $mobile_usage_rules->save();        
        return redirect('/admin/mobile-usage-rules')->with('success', 'Mobile Usage Rule updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $mobile_usage_rules = MobileUsageRule::find($id);
        $mobile_usage_rules->delete();        
        return redirect('/admin/mobile-usage-rules')->with('success', 'Mobile Usage Rule deleted!');
    }

    
    
    
}

app/Http/Controllers/communication_template/create.blade.php
@extends('common.default')
@section('title', 'Category Create')
@section('content')
<!-- Main Content -->
<div id="content">
   <div class="container-fluid" style="margin-top: 20px;">
         <div class="d-sm-flex align-items-center justify-content-between pb-4">
            <h1 class="h3 mb-0 text-gray-800 border-left-primary  h-100 px-1 text-capitalize">add Communication Template</h1>
             <a href="{{url('admin/communication-template')}}" class="d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> &nbsp; Back</a>
        </div>
   <div class="container">
      <!-- Outer Row -->
      <div class="row justify-content-center">
         <div class="card login-card" style="width: 100%;">
            <div class="card-body p-0">
               <!-- Nested Row within Card Body -->
               <div class="row">
                  <div class="col-lg-12">
                     <div class="p-5">
                        @if ($errors->any())
                           <div class="alert alert-danger">
                             <ul>
                                 @foreach ($errors->all() as $error)
                                   <li>{{ $error }}</li>
                                 @endforeach
                             </ul>
                           </div><br />
                        @endif
                        <form class="user" action="{{ route('communication-template.store') }}" method="POST">
                           @csrf

                           <div class="form-group">
                              <label for="name" class="mr-sm-2">Subject:</label>
                              <input type="text" class="form-control form-control-user"
                              id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Subject Name" name="subject" value="{{ old('subject') }}">
                           </div>
                           <div class="form-group">
                              <label for="name" class="mr-sm-2">Template Content:</label>
                              <textarea class="ckeditor form-control" name="template-content"></textarea>
                           </div>
                           <div class="form-group">
                              <label for="name" class="mr-sm-2">SMS:</label>
                              <textarea  class="form-control form-control-user"
                              id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter SMS" name="sms" value="{{ old('sms') }}"></textarea>
                           </div>
                           
                           <a href="#" class="">
                           <button type="submit" class="btn btn-primary mt-4">Submit</button>
                           </a>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      
   </div>
</div>
</div>
<script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.ckeditor').ckeditor();
    });
</script>
<!-- End of Main Content -->
@stop

resources/views/admin/mobileusagerule/create.blade.php
@extends('common.default')
@section('title', 'Category Create')
@section('content')
<!-- Main Content -->
<div id="content">
   <div class="container-fluid" style="margin-top: 20px;">
        
        
         <div class="sub-headeing">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center   text-center text-sm-left" style="padding: 0px 20px;">
        <h3 class="font-w600   js-appear-enabled animated fadeIn" data-toggle="appear" style="color:#575757;font-weight: 600!important;font-size:20px">Add Mobile No. Usage Rules</h3>
        <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
        <span class="d-inline-block js-appear-enabled animated fadeIn" data-toggle="appear" data-timeout="350">
        <a  href="{{url('admin/mobile-usage-rules')}}" class="btn btn-primary btn-sm js-click-ripple-enabled" data-toggle="click-ripple" >
        <i class="fas fa-chevron-left mr-1"></i> Back
        </a>
        </span>
        </div>
        </div>
        </div>
        
   <div class="container">
      <!-- Outer Row -->
      <div class="row justify-content-center" style="margin-top: 120px;">
         <div class="card login-card" style="width: 500px;">
            <div class="card-body p-0">
               <!-- Nested Row within Card Body -->
               <div class="row">
                  <div class="col-lg-12">
                     <div class="p-5">
                        @if ($errors->any())
                           <div class="alert alert-danger">
                             <ul>
                                 @foreach ($errors->all() as $error)
                                   <li>{{ $error }}</li>
                                 @endforeach
                             </ul>
                           </div><br />
                        @endif
                        <form class="user" action="{{ route('mobile-usage-rules.store') }}" method="POST">
                           @csrf
                           <div class="form-group">
                              <label for="name" class="mr-sm-2">Enter Rule Name</label>
                              <input type="text" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Rule Name" name="name" value="{{ old('name') }}">
                           </div>
                           
                           <a href="#" class="">
                           <button type="submit" class="btn btn-primary btn-user btn-block mt-4">Submit</button>
                           </a>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      
   </div>
</div>
</div>
<!-- End of Main Content -->
@stop

resources/views/admin/mobileusagerule/edit.blade.php
@extends('common.default')
@section('title', 'Edit Category')
@section('content')
<!-- Main Content -->
<div id="content">
   <div class="container-fluid" style="margin-top:15px;">
      
        <div class="sub-headeing">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center   text-center text-sm-left" style="padding: 0px 20px;">
        <h3 class="font-w600   js-appear-enabled animated fadeIn" data-toggle="appear" style="color:#575757;font-weight: 600!important;font-size:20px">Mobile No. Usage Rules</h3>
        <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
        <span class="d-inline-block js-appear-enabled animated fadeIn" data-toggle="appear" data-timeout="350">
        <a  href="{{url('admin/mobile-usage-rules')}}" class="btn btn-primary btn-sm js-click-ripple-enabled" data-toggle="click-ripple" >
        <i class="fas fa-chevron-left mr-1"></i> Back
        </a>
        </span>
        </div>
        </div>
        </div>
        
        
   <div class="container">
      <!-- Outer Row -->
      <div class="row justify-content-center"style="margin-top:80px;">
         <div class="card login-card" style="width: 500px;">
            <div class="card-body p-0">
               <!-- Nested Row within Card Body -->
               <div class="row">
                  <div class="col-lg-12">
                     <div class="p-5">
                        @if ($errors->any())
                        <div class="alert alert-danger">
                           <ul>
                               @foreach ($errors->all() as $error)
                               <li>{{ $error }}</li>
                               @endforeach
                           </ul>
                        </div>
                        <br /> 
                        @endif
                        <form method="post" action="{{ route('mobile-usage-rules.update', $mobile_usage_rules->id) }}">
                           @method('PATCH') 
                           @csrf
                        
                           
                           <div class="form-group">
                              <label for="name" class="mr-sm-2">Edit Rule Name</label>
                              <input type="text" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Rule Name" name="name" value="{{$mobile_usage_rules->name}}">
                           </div>
                           
                           <a href="#" class="">
                           <button type="submit" class="btn btn-primary btn-user btn-block mt-4">Update</button>
                           </a>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      
   </div>
</div>
</div>
<!-- End of Main Content -->
@stop
 

resources/views/admin/mobileusagerule/index.blade.php
@extends('common.default')
@section('title', 'Category List')
@section('content')
<!-- Main Content -->
<div id="content">
   <!-- Begin Page Content -->
   <div class="container-fluid" style="margin-top:15px;">
      <!-- Page Heading -->
      <!-- DataTales Example -->
      
      
     
        
        <div class="bg-primary-dark-op">
        <div class="content content-narrow content-full">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center   text-center text-sm-left" style="padding: 0px 20px;">
                <div class="flex-sm-fill">
                    <h3 class="font-w600   js-appear-enabled animated fadeIn" data-toggle="appear" style="color:#575757;font-weight: 600!important;font-size:20px">Mobile No. Usage Rules</h3>
                    
                </div>
                <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
                    <span class="d-inline-block js-appear-enabled animated fadeIn" data-toggle="appear" data-timeout="350">
                        
                       <a href="{{url('admin/mobile-usage-rules/create')}}">  <button class="btn btn-danger btn-sm"    type="button" id="dropdownMenuButton">
                     <i class="fas fa-plus"></i> &nbsp; Add Mobile No. Usage Rules
                     </button></a>
                        
                        <a  href="{{url('admin/campaign/dashboard')}}" class="btn btn-primary btn-sm    js-click-ripple-enabled" data-toggle="click-ripple" >
                            <i class="fas fa-chevron-left mr-1"></i> Back
                        </a>
                         
                    </span>
                </div>
            </div>
        </div>
    </div>
        
        
      <br>
     
      <div class="card ">
         <div class="card-body" >
               @if(session()->get('success'))
          <div class="alert alert-success">
            {{ session()->get('success') }}  
          </div>
       @endif
            <div class="table-responsive">
               <table class="table  table-striped" id="dataTable" width="100%" cellspacing="0" style="margin-top: 35px !important; width: 100%;">
                  <thead>
                     <tr style="text-transform: capitalize;color: #FFF;background-color: #d33f3e"  >
                        <th >SN</th>
                        <th>Mobile Number Usage Rule ID</th>
                        <th>Mobile Number Usage Rule Name</th>
                        <th>Created By</th>
                        <th>Updated By</th>
                        <th>Created Date/Time</th>
                        <th>Updated Date/Time</th>
                        <th>Action</th>
                        <th>Status</th>
                        
                     </tr>
                  </thead>
                  <tbody style="text-align: center">
                     @forelse($mobile_usage_rules as $index=> $rules)
                      
                    <tr>
                        <td scope="row">{{++$index}}</td>
                        <td>{{$rules->id}}</td>
                        <td>{{$rules->name}}</td>
                        <td>{{isset($rules->created_user['name']) ? $rules->created_user['name'] : 'NA'}}</td>
                        <td>{{isset($rules->updated_user['name']) ? $rules->updated_user['name'] : 'NA'}}</td>
                        <td>{{$rules->created_at->format('d M Y')}}/{{$rules->created_at->format('g:i A')}}</td>
                        <td>{{$rules->updated_at->format('d M Y')}}/{{$rules->updated_at->format('g:i A')}}</td>
                        
                        <td>
                           <a href="{{ route('mobile-usage-rules.show',$rules->id) }}"><span style="color: blue;padding:5px;"><i class="fas fa-eye fa-primary fa-md"> </i></span></a>
                           
                           <a href="{{ route('mobile-usage-rules.edit',$rules->id)}}"><span style="color: black;padding:5px;"   ><i class="fas fa-edit fa-primary fa-md"></i></span></a>
                            
                           
                        </td>
                        <td>
                            
                              <input data-id="{{$rules->id}}" class="toggle-class categoryStatus" type="checkbox" 
                              data-onstyle="success" data-offstyle="danger" data-toggle="toggle" data-on="Active" 
                              data-off="InActive" {{ $rules->status ==1 ? 'checked' : '' }}>  
                              <input type="hidden" name="mdoelName" id="mdoelName" value="MobileUsageRule">  
                        </td>
                    </tr>
                    @empty
                
                    @endforelse
                    
                  </tbody>
               </table>
            </div>
         </div>
      </div>
      
 
        
   </div>
   <!-- /.container-fluid -->
</div>
<!-- End of Main Content -->

@stop

resources/views/admin/mobileusagerule/show.blade.php
@extends('common.default')
@section('title', 'Show Category')
@section('content')
<div id="content">
   <div class="container-fluid" style="margin-top:15px;">
      
        <div class="sub-headeing">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center   text-center text-sm-left" style="padding: 0px 20px;">
        <h3 class="font-w600   js-appear-enabled animated fadeIn" data-toggle="appear" style="color:#575757;font-weight: 600!important;font-size:20px">Mobile No. Usage Rules</h3>
        <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
        <span class="d-inline-block js-appear-enabled animated fadeIn" data-toggle="appear" data-timeout="350">
        <a  href="{{url('admin/mobile-usage-rules')}}" class="btn btn-primary btn-sm js-click-ripple-enabled" data-toggle="click-ripple" >
        <i class="fas fa-chevron-left mr-1"></i> Back
        </a>
        </span>
        </div>
        </div>
        </div>
        
        
        
         <div class="container" style="margin-top:50px;">
            <!-- Outer Row -->
            <div class="row justify-content-center">
            <div class="card" style="width: 70%;">
            <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
            <div class="col-lg-12">
            
            
            
            <div class="form-group">
            <div class="card-body col-md-12 col-lg-12">
            
            <p class="show-details">Name</p>
            
            {{$mobile_usage_rules['name']}}
            
            </div>
            </div>
            </div>
            </div>
            </div>
            </div>
            </div>
            </div>
    
   </div>
</div>
@stop