routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear-config', function() {
    Artisan::call('queue:flush');
    return "Config is cleared";
});

Route::get('/', function () {
    return view('auth.login');
    });
Route::post('/logins', 'LoginController@checklogin')->name('login');
Route::get('/logout', function(){
   Auth::logout();
   return Redirect::to('login');
});
Route::group(['middleware'=>['auth'],'prefix'=> 'admin/background-jobs',], function (){

    Route::queueMonitor();
    
});
//admin authenticate

Route::group(['middleware'=>['auth'],'prefix'=> 'admin/',], function (){

    Route::get('dashboard', 'HomeController@dashboard');
    //Get Category Resource
    Route::resource('categories', 'CategoryController');
    //Get Category dashboard
    Route::get('category/dashboard', 'CategoryController@dashboard');
    //Get Category status change
    Route::get('changeStatusCategory', 'CategoryController@changeCategoryStatus');
    //Download Category
    
    Route::get('category/download-category-excel', 'CategoryController@categoryDownload')->name('category.download-category-excel');
    
    
    // ---------------- Communication Template Type ---------------------------
    
    //Get Communication Template Type dashboard
    Route::get('communication_template_type/dashboard', 'CommunicationTemplateTypeController@dashboard');
    
    //Get Communication Template Type Resource
    Route::resource('communication_template_type', 'CommunicationTemplateTypeController');
    
    //Get Communication Template Type status change
    Route::get('changeStatusCommunicationTemplateType', 'CommunicationTemplateTypeController@changeCommunicationTemplateTypeStatus');
    
    //Download Communication Template Type
    
    Route::get('communication_template_type/download-communication_template_type-excel', 'CommunicationTemplateTypeController@communication_template_typeDownload')->name('communication_template_type.download-communication_template_type-excel');
    
    // ---------------- Communication Template Type ---------------------------
    
    
    Route::get('area/download-area-excel', 'AreaController@allAreaDownload')->name('area.download-area-excel');
    
    
    //Get Product Resource
    Route::resource('products', 'ProductController');
    //Get Product dashboard
    Route::get('product/dashboard', 'ProductController@dashboard');
    //Get Product status change
    Route::get('changeStatusProduct', 'ProductController@changeProductStatus');
    //Download Category
    
    Route::get('product/download-product-excel', 'ProductController@productDownload')->name('product.download-product-excel');
    
    //Get User Resource
    Route::resource('users', 'User\UserController');
    Route::get('user/download-user-excel', 'User\UserController@userDownload')->name('user.download-user-excel');
    Route::resource('roles','User\RoleController');
    //Get User dashboard
    Route::get('user/dashboard', 'User\UserController@dashboard');
    //Get User status change
    Route::get('changeStatusUser', 'User\UserController@changeUserStatus');
    
    //Get State Resource
    Route::resource('states', 'StateController');
    //Get State dashboard
    Route::get('state/dashboard', 'StateController@dashboard');
    //Download State
    
    Route::get('state/download-state-excel', 'StateController@stateDownload')->name('state.download-state-excel');
    //Get City Resource
    Route::resource('cities', 'CityController');
    //Get City dashboard
    Route::get('city/dashboard', 'CityController@dashboard');
    //Upload City
    Route::post('city/upload-city-excel', 'CityController@uploadCity')->name('city.upload-city-excel');
    //Download city
    Route::get('city/download-city-excel', 'CityController@cityDownload')->name('city.download-city-excel');
    Route::get('city/download-allcity-excel', 'CityController@allCityDownload')->name('allcity.download-allcity-excel');
    //Get Area Resource
    Route::resource('areas', 'AreaController');
    //Upload Area
    Route::post('area/upload-area-excel', 'AreaController@uploadArea')->name('area.upload-area-excel');
    //Get Area dashboard
    Route::get('area/dashboard', 'AreaController@dashboard');
    Route::get('get-city-list','AreaController@getCityList');
    Route::get('get-area-list','AreaController@getAreaList');
    
    //Get VoucherType Resource
    Route::resource('vouchertype', 'Campaign\VoucherTypeController');
    //Get VoucherType Dashboard
    Route::get('voucher-type/dashboard', 'Campaign\VoucherTypeController@dashboard');
    Route::get('voucher-type/download-voucher-type-excel', 'Campaign\VoucherTypeController@voucherTypeDownload')->name('voucher-type.download-voucher-type-excel');
    //Get VoucherType Resource
    Route::resource('voucherspecification', 'Campaign\VoucherSpecificationController');
    //Get VoucherType Dashboard
    Route::get('voucher-specification/dashboard', 'Campaign\VoucherSpecificationController@dashboard');
    Route::get('voucher-specification/download-voucher-specification-excel', 'Campaign\VoucherSpecificationController@voucherSpecificationDownload')->name('voucher-specification.download-voucher-specification-excel');
    //post ajax request for checking values exists or not
    Route::post('getVoucher_specification','Campaign\VoucherSpecificationController@getVoucher_specification');
    
    //Get Delivery Mechanic Type Resource
    Route::resource('deliverymechanictype','Campaign\DeliveryMechanicTypeController');
    //Get Delivery Mechanic Type Dashboard

    Route::get('deliverymechanic-type/dashboard', 'Campaign\DeliveryMechanicTypeController@dashboard');
    Route::get('deliverymechanic-type/download-deliverymechanic-type-excel', 'Campaign\DeliveryMechanicTypeController@deliveryMechanicTypeDownload')->name('deliverymechanic-type.download-deliverymechanic-type-excel');
    //Get Promo TypeResource
    Route::resource('promotype','Campaign\PromoTypeController');
    //Get Promo Type Dashboard
    Route::get('promo-type/dashboard', 'Campaign\PromoTypeController@dashboard');
    Route::get('promo-type/download-promo-type-excel', 'Campaign\PromoTypeController@promoTypeDownload')->name('promo-type.download-promo-type-excel');
    //Get Company Resource
    Route::resource('companies','Campaign\CompanyController');
    //Get Company Dashboard
    Route::get('company/dashboard', 'Campaign\CompanyController@dashboard');
    Route::get('company/download-company-excel', 'Campaign\CompanyController@companyDownload')->name('company.download-company-excel');
    //Get Campaign Type Resource
    Route::resource('campaigntype','Campaign\CampaignTypeController');
    //Get Campaign Type Dashboard
    Route::get('campaign-type/dashboard', 'Campaign\CampaignTypeController@dashboard');
    
    //Get Venue  Resource
    Route::resource('venues','Pd\VenueController');
    //Get Venue  Resource
    Route::resource('venue-qc','Pd\VenueQcController');
    Route::resource('qc-rejected-venue','Pd\QCRejectedVenueController');
    //Get Venue  Resource
    Route::resource('target-assign','Pd\TargetAssignController');
    //Get Venue  Dashboard
    Route::get('venue/dashboard', 'Pd\VenueController@dashboard');
    //Get Product List On Venue Module
    Route::get('get-product-list','Pd\VenueController@getProductList');
    //Upload Venue Location On Venue Module
    Route::post('venue/upload-venue-location-excel', 'Pd\VenueController@uploadVenueLocation')->name('venue.upload-venue-location-excel');
    
    //Get Campaign  Resource
    Route::resource('campaigns','Campaign\CampaignController');
    //Get Campaign Dashboard
    Route::get('campaign/dashboard','Campaign\CampaignController@dashboard');
    //Get Category Export Excel
    Route::get('export_category/excel', 'CategoryController@categoryExportExcel')->name('export_category.excel');
    //Get Product Rule  Resource
    Route::resource('productrules','ProductRuleController');
    Route::get('changingProduct', 'ProductRuleController@changingProduct');
    //Get Generate Code  Resource
    Route::resource('generate_codes','Campaign\GenerateCodesController');
    
    Route::get('cronjob','CronJobController@store');
    
    Route::get('generate_code/csv-download/{id}','Campaign\GenerateCodesController@csvDownload');
    
    Route::resource('mobile-usage-rules','Campaign\MobileUsageRuleController');
    //Get Code  Resource
    Route::get('generate_code/voucher_code/{id}','Campaign\GenerateCodesController@allVoucherCode')->name('generate_code.voucher_code');
    Route::get('generate_code/download-voucher-excel/{id}', 'Campaign\GenerateCodesController@voucherCodeDownload')->name('voucher.download-voucher-excel');
    // Get ProductList Dropdown on behalf of campaign ID
    Route::get('get_genproductList','Campaign\GenerateCodesController@get_genProductList');

    // Get Product NameList Dropdown on behalf of campaign ID
    Route::get('get_genproductName','Campaign\GenerateCodesController@get_genProductName');
    //Campaign Details Resource
    Route::resource('campaign_details','Campaign\CampaignDetailsController');
    // Get ProductRuleList for Campaign Detail Page Dropdown on behalf of product ID
    Route::get('get_ProductRuleList','Campaign\CampaignDetailsController@get_ProductRuleList');
    //Tag Campaign Venue Resource
    Route::resource('tag_campaign_venues','Campaign\TagCampaignVenueController');    
    Route::get('tag_campaign_venues/{campaign_id}/{product_id}','Campaign\TagCampaignVenueController@show')->name('tag_campaign_venues.show');

app/Http/Controllers/User/RoleController.php
<?php

    

namespace App\Http\Controllers\User;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;


use App\Http\Requests\StoreRoleRequest;
use App\Http\Requests\UpdateRoleRequest;
use Spatie\Permission\Models\Role;

use Spatie\Permission\Models\Permission;

use DB;

    

class RoleController extends Controller

{

    /**

     * Display a listing of the resource.

     *

     * @return \Illuminate\Http\Response

     */

    /*function __construct()

    {

         $this->middleware('permission:role-list|role-create|role-edit|role-delete', ['only' => ['index','store']]);

         $this->middleware('permission:role-create', ['only' => ['create','store']]);

         $this->middleware('permission:role-edit', ['only' => ['edit','update']]);

         $this->middleware('permission:role-delete', ['only' => ['destroy']]);

    }*/

    

    /**

     * Display a listing of the resource.

     *

     * @return \Illuminate\Http\Response

     */

    public function index(Request $request)

    {

        $roles = Role::orderBy('id','DESC')->paginate(5);

        return view('roles.index',compact('roles'))

            ->with('i', ($request->input('page', 1) - 1) * 5);

    }

    

    /**

     * Show the form for creating a new resource.

     *

     * @return \Illuminate\Http\Response

     */

    public function create()

    {

        $permissions = Permission::all()->pluck('name', 'id');

        return view('roles.create',compact('permissions'));

    }

    

    /**

     * Store a newly created resource in storage.

     *

     * @param  \Illuminate\Http\Request  $request

     * @return \Illuminate\Http\Response

     */

    public function store(StoreRoleRequest $request)

    {

        $role = Role::create(['name' => $request->input('name')]);

        $role->permissions()->sync($request->input('permissions', []));

    

        return redirect()->route('roles.index')

                        ->with('success','Role created successfully');

    }

    /**

     * Display the specified resource.

     *

     * @param  int  $id

     * @return \Illuminate\Http\Response

     */

    public function show($id)

    {

        $role = Role::find($id);

        $rolePermissions = Permission::join("role_has_permissions","role_has_permissions.permission_id","=","permissions.id")

            ->where("role_has_permissions.role_id",$id)

            ->get();

    

        return view('roles.show',compact('role','rolePermissions'));

    }

    

    /**

     * Show the form for editing the specified resource.

     *

     * @param  int  $id

     * @return \Illuminate\Http\Response

     */

    public function edit(Role $role)

    {

       /* $role = Role::find($id);
*/
        /*$permission = Permission::get();

        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id",$id)

            ->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')

            ->all();*/
        $permissions = Permission::all()->pluck('name', 'id');

        $role->load('permissions');

    

        return view('roles.edit',compact('role','permissions'));

    }

    

    /**

     * Update the specified resource in storage.

     *

     * @param  \Illuminate\Http\Request  $request

     * @param  int  $id

     * @return \Illuminate\Http\Response

     */

    public function update(UpdateRoleRequest $request,Role $role)

    {
    

        /*$role = Role::find($id);

        $role->name = $request->input('name');

        $role->save();*/

    

        /*$role->syncPermissions($request->input('permission'));*/

        $role->name = $request->input('name');

        $role->save();
        $role->permissions()->sync($request->input('permissions', []));

        return redirect()->route('roles.index')

                        ->with('success','Role updated successfully');

    }

    /**

     * Remove the specified resource from storage.

     *

     * @param  int  $id

     * @return \Illuminate\Http\Response

     */

public function destroy($id)

    {

        DB::table("roles")->where('id',$id)->delete();

        return redirect()->route('roles.index')

                        ->with('success','Role deleted successfully');

    }

}

app/Http/Controllers/communication_template/create.blade.php
@extends('common.default')
@section('title', 'Category Create')
@section('content')
<!-- Main Content -->
<div id="content">
   <div class="container-fluid" style="margin-top: 20px;">
         <div class="d-sm-flex align-items-center justify-content-between pb-4">
            <h1 class="h3 mb-0 text-gray-800 border-left-primary  h-100 px-1 text-capitalize">add Communication Template</h1>
             <a href="{{url('admin/communication-template')}}" class="d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> &nbsp; Back</a>
        </div>
   <div class="container">
      <!-- Outer Row -->
      <div class="row justify-content-center">
         <div class="card login-card" style="width: 100%;">
            <div class="card-body p-0">
               <!-- Nested Row within Card Body -->
               <div class="row">
                  <div class="col-lg-12">
                     <div class="p-5">
                        @if ($errors->any())
                           <div class="alert alert-danger">
                             <ul>
                                 @foreach ($errors->all() as $error)
                                   <li>{{ $error }}</li>
                                 @endforeach
                             </ul>
                           </div><br />
                        @endif
                        <form class="user" action="{{ route('communication-template.store') }}" method="POST">
                           @csrf

                           <div class="form-group">
                              <label for="name" class="mr-sm-2">Subject:</label>
                              <input type="text" class="form-control form-control-user"
                              id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Subject Name" name="subject" value="{{ old('subject') }}">
                           </div>
                           <div class="form-group">
                              <label for="name" class="mr-sm-2">Template Content:</label>
                              <textarea class="ckeditor form-control" name="template-content"></textarea>
                           </div>
                           <div class="form-group">
                              <label for="name" class="mr-sm-2">SMS:</label>
                              <textarea  class="form-control form-control-user"
                              id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter SMS" name="sms" value="{{ old('sms') }}"></textarea>
                           </div>
                           
                           <a href="#" class="">
                           <button type="submit" class="btn btn-primary mt-4">Submit</button>
                           </a>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      
   </div>
</div>
</div>
<script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.ckeditor').ckeditor();
    });
</script>
<!-- End of Main Content -->
@stop

resources/views/admin/user/create.blade.php
@extends('common.default')
@section('title', 'User Create')
@section('content')
<!-- Main Content -->
<div id="content">
   <div class="container-fluid" style="margin-top: 20px;">
          <div class="d-sm-flex align-items-center justify-content-between pb-4">
            <h1 class="h3 mb-0 text-gray-800 border-left-primary  h-100 px-1 text-capitalize"> Add Users</h1>
             <a href="{{url('admin/users')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> &nbsp; Back</a>
        </div>
   <div class="container">
      <!-- Outer Row -->
      <div class="row justify-content-center">
         <div class="card login-card small_forms">
            <div class="card-body p-0">
               <!-- Nested Row within Card Body -->
               <div class="row">
                  <div class="col-lg-12">
                     <div class="p-5">
                        @if ($errors->any())
                           <div class="alert alert-danger">
                             <ul>
                                 @foreach ($errors->all() as $error)
                                   <li>{{ $error }}</li>
                                 @endforeach
                             </ul>
                           </div>
                        @endif
                        <form class="user" action="{{ route('users.store') }}" method="POST" enctype="multipart/form-data">
                           @csrf
                           <div class="form-group">
                              <label>Name <span class="required-field">*</span></label>
                              <input type="text" class="form-control" placeholder="Name" name="name" id="name" value="{{ old('name') }}">
                           <!--@if($errors->has('name'))
                           <div class="error">{{ $errors->first('name') }}</div>
                           @endif-->
                           </div>
                           
                       
                           <div class="form-group">
                              <label>Phone <span class="required-field">*</span></label>
                              <input type="text" class="form-control" placeholder="Phone"  name="phone" id="phone" value="{{ old('phone') }}">
                              <!--@if($errors->has('phone'))
                              <div class="error">{{ $errors->first('phone') }}</div>
                              @endif-->
                           </div>
                           <div class="form-group">
                              <label>Email <span class="required-field">*</span></label>
                              <input type="email" class="form-control" placeholder="Email"  name="email" id="txtEmail" onkeyup="ValidateEmail();" value="{{ old('email') }}">
                               <span id="lblError" style="color: red"></span>
                           <!--@if($errors->has('email'))
                           <div class="error">{{ $errors->first('email') }}</div>
                           @endif-->
                           </div>

                           <div class="form-group">
                              <label>Role<span class="required-field">*</span></label>
                              <select name="role" class="form-control">

                              <option value="0">Select Role</option>
                              @forelse($roles as $role)
                              <option value="{{$role->id}}" {{ (old('role') ==  $role->id)? 'Selected' : ''}}>{{$role->name}}</option>
                              @empty
                             <p>No Role List</p>
                             @endforelse
                              </select>
                              
                              <!--@if($errors->has('role'))
                              <div class="error">{{ $errors->first('role') }}</div>
                              @endif-->
                           </div>
                            <div class="form-group">
                              <label>Password <span class="required-field">*</span></label>
                              <input type="password" class="form-control" placeholder="Password"  name="password" id="txtpassword">
                              <!--@if($errors->has('password'))
                              <div class="error">{{ $errors->first('password') }}</div>
                              @endif-->
                           </div>
                           <div class="form-group">
                              <label>Confirm Password <span class="required-field">*</span></label>
                              <input type="password" class="form-control" placeholder="Confirm Password"  name="confirm_pass" id="txtconfirmpass" onChange="checkPasswordMatch();">
                              <!--@if($errors->has('password'))
                              <div class="error">{{ $errors->first('password') }}</div>
                              @endif-->
                           </div> 
                           <div class="form-group">
                              <label>Status<span class="required-field">*</span></label>
                              <select name="status" class="form-control">

                              
                              
                              <option value="0" {{ (old('status') ==  '0')? 'Selected' : ''}}>Inactive</option>
                              <option value="1" {{ (old('status') ==  '1')? 'Selected' : ''}}>Active</option>
                              
                              </select>
                              
                              <!--@if($errors->has('role'))
                              <div class="error">{{ $errors->first('role') }}</div>
                              @endif-->
                           </div>
                           <a href="#" class="">
                           <button type="submit" class="btn btn-primary  btn-block mt-4">Submit</button>
                           </a>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      
   </div>
</div>
</div>
<!-- End of Main Content -->
@stop

resources/views/admin/user/index.blade.php
@extends('common.default')
@section('title', 'User List')
@section('content')
<!-- Main Content -->
<div id="content">
   <!-- Begin Page Content -->
   <div class="container-fluid" style="margin-top: 20px;">
      <!-- Page Heading -->
      <!-- DataTales Example -->
          <div class="d-sm-flex align-items-center justify-content-between pb-4">
            <h1 class="h3 mb-0 text-gray-800 border-left-primary  h-100 px-1 text-capitalize">Users</h1>
             <a href="{{url('admin/user/dashboard')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> &nbsp; Back</a>
        </div>
        
      <div class="card shadow ">
         <div class="card-header d-none d-sm-block">
            <nav class="navbar navbar-expand">
               <ul class="navbar-nav ml-auto">
                  <li style="margin-right: 20px;"><a href="{{url('admin/users/create')}}">  <button class="btn btn-danger btn-sm"    type="button" id="dropdownMenuButton">
                     <i class="fas fa-plus"></i> &nbsp; Add User
                     </button></a>
                  </li>
                  <!--<li style="margin-right: 20px;">  <button class="btn btn-primary btn-sm"     type="button" id="dropdownMenuButton">
                     <i class="fas fa-file-import"></i> &nbsp; Import User
                     </button>
                  </li>
                  <li style="margin-right: 20px;">  <button class="btn btn-primary btn-sm" type="button" id="dropdownMenuButton">
                     <i class="fas fa-print"></i> &nbsp; Print User
                     </button>
                  </li>
                  <li class="nav-item dropdown" ml-2>
                     <div class="dropdown">
                        <button class="btn btn-primary dropdown-toggle btn-sm" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-file-export"></i>&nbsp; Export User
                        </button>
                        <div class="dropdown-menu animated--fade-in" aria-labelledby="dropdownMenuButton ">
                           <a class="dropdown-item font-weight-bold" href="abc.xlsx"><i class="fas fa-file-excel"></i> &nbsp; Export to Excel</a>
                           <a class="dropdown-item font-weight-bold" href="abc.docx"><i class="fas fa-file-word"></i> &nbsp; Export to Word</a>
                           <a class="dropdown-item font-weight-bold" href="abc.pdf"><i class="fas fa-file-pdf"></i> &nbsp;Export to PDF</a>
                        </div>
                     </div>
                  </li>-->
               </ul>
            </nav>
         </div>
    
         <div class="card-body" >
                  @if(session()->get('success'))
          <div class="alert alert-success">
            {{ session()->get('success') }}  
          </div>
       @endif
       
       
       
            <div class="table-responsive">
               <table class="table table-striped table-bordered" id="dataTable" width="100%" cellspacing="0" style="margin-top: 35px !important; width: 100%;">
                  <thead>
                     <tr style="text-transform: capitalize;color: #FFF;background-color: #d33f3e"  >
                        <th>SN</th>
                        <th>User Id</th>
                        <th>Name</th>
                        <th>Role</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Created By</th>
                        <th>Updated By</th>
                        <th>Created Date/Time</th>
                        <th>Updated Date/Time</th>
                        <th>Action</th>
                        <th>Status</th>
                     </tr>
                  </thead>
                  <tbody style="text-align: center">
                     @forelse($list as $index=>$data)
                      
                    <tr>
                        <th scope="row">{{++$index}}</th>
                        <td>{{$data->id}}</td>
                        <td>{{$data->name}}</td>
                        <td>{{$data->user_role['name']}}</td>
                        <td>{{$data->phone}}</td>
                        <td>{{$data->email}}</td>
                       
                        
                        
                        
                        <td>
                           <a href="{{ route('users.show',$data->id) }}"><span style="color: blue;padding:5px;"><i class="fas fa-eye fa-primary fa-md"> </i></span></a>
                           
                           <a href="{{ route('users.edit',$data->id)}}"><span style="color: black;padding:5px;"   ><i class="fas fa-edit fa-primary fa-md"></i></span></a>
                            
                        </td>
                        <td>
                            
                              <input data-id="{{$data->id}}" class="toggle-class categoryStatus" type="checkbox" 
                              data-onstyle="success" data-offstyle="danger" data-toggle="toggle" data-on="Active" 
                              data-off="InActive" {{ $data->status ==1 ? 'checked' : '' }}>  
                              <input type="hidden" name="mdoelName" id="mdoelName" value="User">  
                        </td> 
                    </tr>
                    @empty
                    
                    @endforelse
                    
                  </tbody>
               </table>
            </div>
         </div>
      </div>
   </div>
   <!-- /.container-fluid -->
</div>
<!-- End of Main Content -->

@stop

resources/views/admin/user/show.blade.php
@extends('common.default')
@section('title', 'Show User')
@section('content')
<div id="content">
   <div class="container-fluid" style="margin-top: 20px;">
       
       
             
       <div class="d-sm-flex align-items-center justify-content-between pb-4">
            <h1 class="h3 mb-0 text-gray-800 border-left-primary  h-100 px-1 text-capitalize">Users</h1>
             <a href="{{url('admin/users')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> &nbsp; Back</a>
        </div>

        <table class="table  table-striped"   width="100%" cellspacing="0" style="margin-top: 35px !important;">
                  <thead>
                     <tr style="text-transform: capitalize;color: #FFF;background-color: #d33f3e"  >
                        <th>ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Role</th>
                        <th>Status</th>
                        
                     </tr>
                  </thead>
                  <tbody style="text-align: center">
                     
                      
                    <tr>
                        <td>  	{{ $users->id }} </td>
                        <td>  	{{ $users->name }} </td>
                        
                        <td>   	   {{ $users->email }} </td>
                        
                         <td>  {{ $users->phone }}  </td>
                        <td>   {{ $users->user_role['name'] }} </td>
                        <td>       {{ ($users->status == '1')? 'Active':'Inactive' }}</td>
                 
                    
                  </tbody>
               </table>
              
   </div>
</div>
@stop